language: node_js
node_js:
- stable
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: XxufGCTDZRozeQbybGQlaN2wupJeVLlJcGjsQlarWaNhNixlNERKYMChX18gur9jNmh2xY3xg9xWktghHPnQrAq/cEunuOCugpSA9oTwkBvCClIkUuPIjo4CAceyVf7Hvpe4lfqoVGjKEjgT1f7csoLhSdllJgd5tPtl05YAjWvfKKwYt38CBrs3btdiFGlVL3gmxvmY4f8cW1VVorrqT7v0uyerz12IjtC+ndxUB/r7UWkyIFQK1OOqZkk1eNp93iyx9kNVTc26qpyjIFbX+1VPMbQRV65iceL2ngkwRHKqjTv6KGv0zhVWG4Jt778FegyywZQRUBwDI6rOqd/4vhSpkV9HZwYDcFxISw9wg5ro+/tzoJuEYtyOiAiCUGd5+IpNFcusn2SSVqhAfc2y2pD99zEEKC3XlJ3mlf/aC1cW8gN7x9nVbt9UZczP1az8ztFiBYX/i831o6CqnbQGRFx7x7cMTzZJPQ7oZPfPPZnbWajlN33QaBbjqb8BcYGP6Y+IkG6aDyTZmT1PI7Go6WtDHPAS2NZPCetvpKdCNySK1cco7GTeCDBRDxbcXjx+pJSHeI9v78w/EAAnbavOUMWFobzHWGHeguWY5jwU/dMc8ubMXWUURCpaM10KuTHQvBZu3w5r2kmJXkho6rIl2X5SqX1KaCyFc2SC8U5dJ4w=
  app: lets-talk-corona
  on:
    repo: dev-hg20/lets-talk-corona
